language: scala
jdk:
  - openjdk8
scala:
  - 2.12.10
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2
script: 
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coverall
